import {
  navFontSize,
  linkTextTransform,
  linkFontWeight,
  radius,
} from "./styleTypes";

export default {
  componentName: "smartHeader",
  cms: {
    style: {
      background: "Header background",
      navColor: "Nav color",
      navHoverColor: "Hover color",
      navFont: "Font size",
      textTransform: "Text transform",
      fontWeight: "Font weight",
      titleFontSize: "Title font size",
      bottomSpace: "Title bottom space",
      contentSpace: "Content bottom space",
      buttonColor: "Button color",
      buttonFontSize: "Font size",
      borderColor: "Color",
      buttonHoverColor: "Hover color",
      borderHoverColor: "Hover color",
      buttonRadius: "Shape",
    },
    links: {
      link1: "Link 1",
      // url1: "Url",
      link2: "Link 2",
      // url2: "Url",
      link3: "Link 3",
      // url3: "Url ",
      buttonTitle: "Button Title",
      buttonUrl: "Button url",
    },
    content: {
      title: "Title",
      content: "Content",
      buttonTitle: "Link title",
    },
    media: {
      logo: "Logo url",
      logoAlt: "Brand image alt",
      bgImage: "Cover image",
    },
  },
  styleType: {
    style: {
      background: { type: "color" },
      navColor: { type: "color" },
      navHoverColor: { type: "color" },
      navFont: { ...navFontSize },
      textTransform: { ...linkTextTransform },
      fontWeight: { ...linkFontWeight },
      titleFontSize: { ...navFontSize },
      bottomSpace: { ...navFontSize },
      contentSpace: { ...navFontSize },
      buttonColor: { type: "color" },
      buttonFontSize: { ...navFontSize },
      borderColor: { type: "color" },
      buttonHoverColor: { type: "color" },
      borderHoverColor: { type: "color" },
      buttonRadius: { ...radius },
    },
    content: {
      title: "Title",
      content: "Content",
      buttonTitle: "Link title",
    },
    media: {
      logo: "Logo url",
      logoAlt: "Logo alt text *",
      bgImage: "Cover image",
    },
  },
  props: {
    //editable part
    style: {
      background: "",
      navFont: "16px",
      navColor: "#fff",
      navHoverColor: "#000",
      textTransform: "capitalize",
      fontWeight: "500",
      titleFontSize: "30px",
      bottomSpace: "20px",
      contentSpace: "20px",
      buttonColor: "#fff",
      buttonFontSize: "16px",
      borderColor: "#fff",
      buttonHoverColor: "#000",
      borderHoverColor: "#000",
      buttonRadius: "5px",
    },
    links: {
      link1: "Home",
      // url1: "",
      link2: "enterprise",
      // url2: "",
      link3: "pricing",
      // url3: "",
      buttonTitle: "Learn more",
      buttonUrl: "",
    },
    content: {
      title: "<span>What is Lorem Ipsum</span>",
      content: `<span>What is Lorem Ipsum Lorem Ipsum is simply dummy text of the printing
      and typesetting industry Lorem Ipsum has been the industry's
      standard dummy text ever since the</span>`,
    },
    media: {
      logo: "/assets/images/eagle-power.jpg",
      logoAlt: "logo",
      bgImage: "/assets/images/eagle-power.jpg",
    },
    media: {
      logo: "/assets/images/eagle-power.jpg",
      logoAlt: "logo",
      bgImage: "/assets/images/eagle-power.jpg",
    },
  },
};
