const gridFormDefaultProps = {
  componentName: "gridForm",
  cms: {
    style: {
      background: "Form background",
      bodyColor: "Title color",
      inputBg: "Input background",
      inputFontSize: "Input font size",
      borderColor: "Border color",
      inputColor: "Input color",
      inputRadius: "Input shape",
      placeholderColor: "Placeholder color",
      placeholderFontSize: "Placeholder font size ",
      buttonBg: "Button Background",
      buttonHoverBg: "Hover background",
      buttonColor: "Color",
      buttonRadius: "Button shape",
      buttonBorderColor: "Border color",
      buttonHoverColor: "Hover color",
      buttonHoverBorderColor: "Hover Border color",
      buttonFont: "Font size",
      buttonRadius: "button shape",
    },
    media: { email: "Email" },
    content: {
      formTitle: "Title text ",
      fullName: "Full name",
      email: "Email",
      number: "Number",
      city: "City",
      message: "Message text",
      button: "Submit text",
    },
  },
  styleType: {
    style: {
      background: { type: "color" },
      bodyColor: { type: "color" },
      inputBg: { type: "color" },
      inputFontSize: { type: "textField" },
      borderColor: { type: "color" },
      inputColor: { type: "color" },
      inputRadius: { type: "textField" },
      placeholderColor: { type: "color" },
      placeholderFontSize: { type: "textField" },
      buttonFont: { type: "textField" },
      buttonBg: { type: "color" },
      buttonHoverBg: { type: "color" },
      buttonColor: { type: "color" },
      buttonRadius: { type: "textField" },
      buttonBorderColor: { type: "color" },
      buttonHoverColor: { type: "color" },
      buttonHoverBorderColor: { type: "color" },
      buttonFont: { type: "textField" },
      buttonRadius: { type: "textField" },
    },
  },
  props: {
    //editable part
    style: {
      background: "#f2f4f8",
      bodyColor: "#212529",
      inputBg: "",
      inputFontSize: "16",
      inputColor: "#495057",
      borderColor: "",
      inputRadius: "2",
      placeholderColor: "#495057",
      placeholderFontSize: "13",
      buttonFont: "16",
      buttonBg: "#f2f4f8",
      buttonHoverBg: "",
      buttonColor: "#212529",
      buttonRadius: "2",
      buttonBorderColor: "#212529",
      buttonHoverColor: "",
      buttonHoverBorderColor: "",
      buttonFont: "16",
      buttonRadius: "3",
    },
    content: {
      formTitle: `<h2>Contact form</h2>`,
      fullName: "Full name",
      email: "Email",
      number: "Number",
      city: "City",
      message: "Message..",
      button: "Submit",
    },
    media: {
      email: "",
    },
  },
};
export default gridFormDefaultProps;
